# Generated by Django 6.0.7 on 2026-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=100, verbose_name='Nome no Convite (ex: Família Silva)')),
                ('codigo_acesso', models.CharField(max_length=20, unique=True, verbose_name='Senha do Convite de Papel')),
                ('limite_pessoas', models.PositiveIntegerField(verbose_name='Limite total de convidados (incluindo o titular)')),
                ('confirmou', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Confirmou presença?')),
                ('quantidade_vinda', models.PositiveIntegerField(default=0, verbose_name='Quantas pessoas realmente vão')),
                ('nomes_acompanhantes', models.TextField(blank=True, null=True, verbose_name='Nomes das pessoas que vão')),
            ],
        ),
    ]
